# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:


print(np.__version__)
print(np.show_config())


1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
import numpy as np
  
#To show the size of the numpy array I'm creating an array x
x = np.array([1,2,3,4,5])
  
print("Size of the array: ",
      x.size)
  
print("Memory size of one array element in bytes: ",
      x.itemsize)
  
# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:",
      x.size * x.itemsize)

Size of the array:  5
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 40


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
import numpy as np
print(np.info(np.add))

None


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
a = np.zeros(10)
print(a)
a[4]= 1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
x = np.arange(10,49)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x = np.arange(1,10)
a = x[::-1]
print(a)

[9 8 7 6 5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x =  np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x = np.array([1,2,0,0,4,0])
np.nonzero(x)



(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x = np.random.random((3,3,3))
print(x)


[[[7.53862910e-01 2.10970373e-01 2.92254375e-01]
  [6.15666332e-01 2.06326482e-01 9.30561690e-01]
  [1.27083325e-01 4.62847319e-04 7.03182929e-02]]

 [[4.44975316e-01 8.21943410e-01 5.17289399e-01]
  [7.68636160e-01 5.20028980e-01 3.77714694e-01]
  [1.25334663e-01 1.84401105e-01 2.28682820e-01]]

 [[3.65212092e-01 8.37068672e-01 6.89130931e-01]
  [9.46752420e-01 1.68893082e-01 2.56710420e-01]
  [6.57640969e-01 2.48938869e-01 9.07714293e-01]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x = np.random.random((10,10))
print(x)
minimum = x.min()
maximum = x.max()
print(minimum,maximum)

[[0.13854935 0.61233726 0.65812666 0.11383003 0.7771112  0.9970825
  0.78070572 0.87166406 0.96211681 0.37939201]
 [0.43059011 0.91106302 0.35809658 0.59284292 0.97119507 0.4263576
  0.08796825 0.04850516 0.11803668 0.3637279 ]
 [0.32295075 0.46538764 0.2403242  0.89803089 0.82928983 0.20249268
  0.48695304 0.66178983 0.98382307 0.37049635]
 [0.09046248 0.32621814 0.11465715 0.16513875 0.29687466 0.69032181
  0.10997178 0.06316197 0.83965816 0.92616566]
 [0.09188561 0.15005037 0.92741825 0.42868091 0.35616186 0.20031774
  0.18792813 0.98434997 0.36656461 0.35077302]
 [0.05868014 0.5955893  0.40549333 0.74606537 0.49661559 0.47022693
  0.61964526 0.40543648 0.17655506 0.02291527]
 [0.10958435 0.83039182 0.98493747 0.40608481 0.94960285 0.50301336
  0.73945764 0.05057237 0.17994161 0.09692661]
 [0.58874902 0.08477313 0.94162166 0.31514374 0.42978008 0.48100822
  0.61933999 0.69880324 0.29783919 0.90813386]
 [0.31356857 0.59757105 0.22290138 0.19050861 0.27092741 0.93088134
  0.68016506 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x = np.random.random(30)
print(x)
a = np.mean(x)
print(a)

[0.5557026  0.76871482 0.66257849 0.41547139 0.95992166 0.5322622
 0.78967803 0.47072898 0.18500179 0.97441011 0.48763048 0.15125391
 0.37212055 0.26761178 0.85105784 0.35428782 0.10817222 0.96670548
 0.59256739 0.87742172 0.50103745 0.72497068 0.7271782  0.32633727
 0.84022055 0.35512871 0.40967927 0.34073936 0.82199093 0.61928711]
0.5669956267479637


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x = np.ones((6,6))

print("The 2d array\n",x)

x[1:-1,1:-1] = 0
print("The 2d array with 1 on the border and 0 inside\n",x)

The 2d array
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
The 2d array with 1 on the border and 0 inside
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:

x = np.ones((3,3))
print("2D array ")
print(x)
print("0 on the border of the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

2D array 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border of the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
x = np.diag(1+np.arange(4), k = -1)
print (x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x = np.zeros ((8,8), dtype=int)
x[1::2, ::2]= 1
x[::2, 1::2] = 1
print (x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
x = np.array([[0,1], [1,0]])
y = np.tile(x,(4,4))
print (y)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.random((5,5))
xmax, xmin = x.max(), x.min()
y= (x-xmin)/(xmax-xmin)
print (y)

[[0.89474411 0.46656913 0.14372366 0.82891207 0.41082404]
 [0.28907372 0.32842781 0.52066836 0.66736135 0.29258192]
 [0.6868567  0.99940167 0.24442827 0.09771076 1.        ]
 [0.58015125 0.55393154 0.9814545  0.         0.92770623]
 [0.21398938 0.4837613  0.05667255 0.3975439  0.69144562]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x= np.dot(np.ones((5,3)), np.ones((3,2)))
print (x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x= np.arange(11)
print(x)
x[(3 < x) & (x < 8)] *= -1
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z=np.arange(16)
print(z**z)
print(2 << z >> 2)
print(z <- z)
print(1j*z)
print(z/1/1)
print(z<z<z) #This expression is not valid

[                 1                  1                  4
                 27                256               3125
              46656             823543           16777216
          387420489        10000000000       285311670611
      8916100448256    302875106592253  11112006825558016
 437893890380859375]
[    0     1     2     4     8    16    32    64   128   256   512  1024
  2048  4096  8192 16384]
[False False False False False False False False False False False False
 False False False False]
[0. +0.j 0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j
 0. +9.j 0.+10.j 0.+11.j 0.+12.j 0.+13.j 0.+14.j 0.+15.j]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
z = np.array([-5.5,2.3,1.4,-3.2,-5.3])
print(z)
x=np.copysign(np.ceil(np.abs(z)),z)
print(x)
z1=np.abs(z)
print(z1)
z2=np.floor(z1)
print(z2)
z3=np.copysign(z2,z)
print(z3)

[-5.5  2.3  1.4 -3.2 -5.3]
[-6.  3.  2. -4. -6.]
[5.5 2.3 1.4 3.2 5.3]
[5. 2. 1. 3. 5.]
[-5.  2.  1. -3. -5.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x = np.random.randint(0,10,10)
print(x)
y = np.random.randint(0,10,10)
print(y)
print(np.intersect1d(x,y))

[7 4 9 9 4 3 6 0 2 1]
[8 6 5 8 6 8 0 8 6 1]
[0 1 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
print(np.datetime64('today'))
print(np.datetime64('today') - np.timedelta64(1))
print(np.datetime64('today') + np.timedelta64(1))

2022-01-02
2022-01-01
2022-01-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = -15
B = 20
B = np.add(A,B)
A = np.divide(A,2)
A = np.negative(A)
A = np.multiply(A,B)
print(A)

37.5


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
x = np.random.uniform(0,5,10)
print(x)
print(x-x%1)
print(np.floor(x))
print(np.ceil(x))
print(x.astype(int))
print(np.trunc(x))


[3.98006795 1.65119767 4.20468799 1.10416702 2.91080519 3.55306286
 3.35822401 0.5738091  1.8132319  1.49087569]
[3. 1. 4. 1. 2. 3. 3. 0. 1. 1.]
[3. 1. 4. 1. 2. 3. 3. 0. 1. 1.]
[4. 2. 5. 2. 3. 4. 4. 1. 2. 2.]
[3 1 4 1 2 3 3 0 1 1]
[3. 1. 4. 1. 2. 3. 3. 0. 1. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:

Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generator(): 
    for x in range(10):
        yield x
        
Z = np.fromiter(generator(), dtype=float, count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x = np.random.random(10)
print(x)
x.sort()
print(x)

[0.14405677 0.01892388 0.06938254 0.08323979 0.42138268 0.0672465
 0.79445278 0.6991917  0.79733343 0.75411742]
[0.01892388 0.0672465  0.06938254 0.08323979 0.14405677 0.42138268
 0.6991917  0.75411742 0.79445278 0.79733343]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
x = np.arange(10)
print(x)
np.add.reduce(x)

[0 1 2 3 4 5 6 7 8 9]


45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(1,6,5)
B = np.random.randint(1,6,5)
equal = np.allclose(A,B)
print(equal)


False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
import numpy as np
x = np.random.random((10,2))
A,B = x[:,0], x[:,1]
R = np.sqrt(A**2+B**2)
T = np.arctan2(B,A)
print(R)
print(T)

[0.56330555 0.92828127 0.43869015 0.47830397 0.34550698 1.03583453
 0.58437463 0.71839002 0.72707956 0.84030689]
[0.21447476 1.48722402 0.77889668 0.39367247 1.12919933 0.9322956
 0.90534577 0.46147703 0.1770157  0.16529957]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x= np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.69500581 0.00664506 0.65858879 0.07699676 0.35990985 0.06360552
 0.19678973 0.24566273 0.         0.02935048]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
A = np.zeros((10,10), [('x',float),('y',float)])
A['x'], A['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(A)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:

A = np.arange(8)
B = A + 0.5
C = 1.0 / np.subtract.outer(A, B)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
x = np.arange(1001)
np.set_printoptions(threshold=np.inf)
print(x)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x= np.arange(100)
print(x)
y = np.random.uniform(0,100)
print(y)
index = (np.abs(x-y)).argmin()
print(x[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
88.78457194426358
89


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
A = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(A)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
A = np.random.random((10,2))
X,Y = np.atleast_2d(A[:,0]), np.atleast_2d(A[:,1])
B = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(B)



[[0.         0.39555387 0.5209354  1.00806852 0.2031756  0.44588983
  0.63284766 0.53232187 0.34511454 0.88374831]
 [0.39555387 0.         0.2241939  0.75342434 0.47327468 0.57295762
  0.74108353 0.53819837 0.53171569 0.74518125]
 [0.5209354  0.2241939  0.         0.53230239 0.51051586 0.50197842
  0.63111471 0.40729626 0.50503531 0.53128318]
 [1.00806852 0.75342434 0.53230239 0.         0.91920364 0.76082531
  0.75535076 0.59664164 0.83425644 0.29372796]
 [0.2031756  0.47327468 0.51051586 0.91920364 0.         0.25324092
  0.43445403 0.37130239 0.14654789 0.74677495]
 [0.44588983 0.57295762 0.50197842 0.76082531 0.25324092 0.
  0.18975597 0.1643867  0.1085415  0.5374506 ]
 [0.63284766 0.74108353 0.63111471 0.75535076 0.43445403 0.18975597
  0.         0.22528629 0.28839214 0.48529108]
 [0.53232187 0.53819837 0.40729626 0.59664164 0.37130239 0.1643867
  0.22528629 0.         0.25050586 0.38066722]
 [0.34511454 0.53171569 0.50503531 0.83425644 0.14654789 0.1085415
  0.28839214 0.2505058

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
x = np.arange(10, dtype=np.int32)
x = x.astype(np.float32, copy=False)



#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

#File
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
x= np.genfromtxt(s, delimiter=",", dtype=np.int)
print(x)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
x = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(x):
    print(index, value)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
A, B = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
C = np.sqrt(A*A+B*B)
sigma, mu = 1.0, 0.0
D = np.exp(-( (C-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(D)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
x = np.zeros((n,n))
np.put(x, np.random.choice(range(n*n), p, replace=False),1)
print (x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:

x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[ 0.17157352 -0.42488928  0.17176517 -0.33195463  0.11673107  0.04739848
   0.23081254 -0.53806795  0.3813699   0.17526119]
 [-0.41909779  0.09343889  0.24021234  0.47601014  0.05431506 -0.3853693
  -0.1626825   0.27854939 -0.11014665 -0.06522958]
 [-0.01626067 -0.28397197  0.12708489 -0.25271933 -0.16575492  0.36168082
   0.34091462  0.30719864 -0.62433061  0.20615852]
 [-0.2429832  -0.23574038  0.09945988 -0.01182425  0.27813364  0.25314826
  -0.22149762  0.07918811  0.14828967 -0.14617411]
 [ 0.0661066  -0.07450089  0.34644666 -0.18593192 -0.2370911   0.35343504
   0.21370611 -0.22632334  0.18669547 -0.44254262]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
x = np.random.randint(0,10,(3,3))
print(x)
print(x[x[:,1].argsort()])

[[5 5 2]
 [4 9 2]
 [1 3 9]]
[[1 3 9]
 [5 5 2]
 [4 9 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
x= np.random.randint(0,3,(3,10))
print((~x.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
x = np.random.uniform(0,1,10)
y = 0.5
z = x.flat[np.abs(x-y).argmin()]
print(z)

0.6332987581424367


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
x = np.arange(3).reshape(3,1)
print(x)
y = np.arange(3).reshape(1,3)
print(y)
it = np.nditer([x,y,None])
for a,b,c in it: c[...] = a+b
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [51]:
class Array(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = Array(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [52]:
x = np.ones(10)
y = np.random.randint(0,len(x),20)
x += np.bincount(y, minlength=len(x))
print(x)

# Another solution
np.add.at(x, y, 1)
print(Z)

[3. 4. 3. 4. 2. 1. 3. 1. 6. 3.]
[0 1 2 3 4 5 6 7 8 9]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [53]:
x = [1,2,3,4,5,6]
y = [1,3,9,3,4,1]
z = np.bincount(y,x)
print(z)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [55]:
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [56]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)


[[48 40 49 63]
 [52 59 62 61]
 [51 72 40 47]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [58]:
a = np.random.uniform(0,1,100)
b = np.random.randint(0,10,100)
a_sums = np.bincount(b, weights=a)
a_counts = np.bincount(b)
a_means = a_sums / a_counts
print(a_means)


[0.63967845 0.63390878 0.62032658 0.50414147 0.46174769 0.49039704
 0.46180324 0.44436979 0.48431205 0.59004653]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [60]:

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(np.diag(np.dot(A, B)))

[2.05141574 1.7047941  1.91759043 1.0466612  0.75279668]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [69]:
x = np.array([1,2,3,4,5])
y[::4] = x
print(y)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [71]:
x = np.ones((5,5,3))
y = 2*np.ones((5,5))
print(x * y[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [5]:
x = np.arange(25).reshape(5,5)
print(x)
x[[0,1]] = x[[1,0]]
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [8]:
faces = np.random.randint(0,100,(10,3))
A = np.roll(faces.repeat(2,axis=1),-1,axis=1)
A = A.reshape(len(A)*3,2)
A = np.sort(A,axis=1)
B= A.view( dtype=[('p0',A.dtype),('p1',A.dtype)] )
B = np.unique(B)
print(B)

[( 1, 27) ( 1, 46) (20, 56) (20, 59) (27, 46) (30, 55) (30, 85) (35, 42)
 (35, 52) (42, 52) (42, 86) (42, 89) (47, 52) (47, 99) (52, 99) (54, 68)
 (54, 75) (55, 85) (56, 59) (68, 75) (69, 81) (69, 96) (71, 76) (71, 95)
 (76, 95) (77, 88) (77, 98) (81, 96) (86, 89) (88, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [11]:
A = np.bincount([1,1,2,3,4,4,6])
B = np.repeat(np.arange(len(A)), A)
print(B)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [13]:
def average(a, n=3) :
    b = np.cumsum(a, dtype=float)
    b[n:] = b[n:] - b[:-n]
    return b[n - 1:] / n
c = np.arange(20)
print(average(c, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [16]:
from numpy.lib import stride_tricks

def roll(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
A = roll(np.arange(10), 3)
print(A)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [17]:
A = np.random.randint(0,2,100)
np.logical_not(A, out=A)

A = np.random.uniform(-1.0,1.0,100)
np.negative(A, out=A)

array([ 0.78876612, -0.81555409, -0.5793357 ,  0.75885653,  0.72620708,
        0.8469818 ,  0.77766947, -0.61768713,  0.06516575,  0.37594836,
       -0.55407814, -0.25623427,  0.22981727, -0.61256187, -0.99855466,
       -0.59441602,  0.64640167, -0.24479345, -0.40602218,  0.18908015,
       -0.70968413, -0.10428187, -0.87587012,  0.63196029,  0.66876861,
       -0.79851532, -0.85090523,  0.89723664,  0.94917866,  0.69181461,
        0.78073838,  0.69090175,  0.59869422,  0.41183596,  0.20918384,
       -0.63034019, -0.51443505,  0.12253617,  0.27273569, -0.19624667,
        0.720867  ,  0.39844418,  0.91231167,  0.42201153,  0.17113214,
        0.81594503, -0.90651951, -0.89698467,  0.52770718,  0.52745539,
        0.26906279, -0.47619678, -0.23643495, -0.3839164 ,  0.07889674,
        0.44402042,  0.18842473,  0.80257317,  0.07391485,  0.14727342,
        0.28024375,  0.88223509,  0.2373215 ,  0.15700712,  0.06252947,
       -0.68560494,  0.46878672, -0.95886347,  0.73527642,  0.75

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [19]:
def distance(P0, P1, p):
    A = P1 - P0
    B = (A**2).sum(axis=1)
    C = -((P0[:,0]-p[...,0])*A[:,0] + (P0[:,1]-p[...,1])*A[:,1]) / B
    C = C.reshape(len(C),1)
    D = P0 + C*A - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[2.64471089 1.05679664 1.07109856 0.58264744 2.1223718  3.52944162
 5.31657836 1.96529566 3.79768447 8.055064  ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [21]:

def distance(P0, P1, p):
    A = P1 - P0
    B = (A**2).sum(axis=1)
    C = -((P0[:,0]-p[...,0])*A[:,0] + (P0[:,1]-p[...,1])*A[:,1]) / B
    C = C.reshape(len(C),1)
    D = P0 + C*A - p
    return np.sqrt((D**2).sum(axis=1))
    
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.14131768  2.22345211  0.65718828  5.03698569 10.40237629  2.79651156
   4.21093545  2.06007187 10.45303466  1.86448051]
 [ 5.52937506 11.48296091  7.88485554  4.45860152  5.76442709  7.44174101
   3.98975454  7.24491353  1.48113802 10.83319023]
 [ 4.96887538  3.33323764  0.87945926  9.61239666  5.86485624  7.32791689
   3.80881309  6.11962372 11.62924352  4.31389049]
 [ 4.64749649 10.04921234  6.93830861  3.07442475  5.92109229  7.28381463
   3.12824064  6.99207995  2.54762288  9.38340413]
 [ 9.96555285  0.55161053  5.8832168   5.79886167  1.79332773 14.98679391
   3.21035163 13.8139257   5.33303583  2.30097878]
 [ 4.9302492   5.7049392   1.9001292   1.61659066  9.63549366  3.56636447
   1.83795107  3.05256794  7.64121958  5.3428799 ]
 [ 3.83776273 12.54027641 10.30288409  5.87322832  3.08117641 10.12530942
   6.49222827  9.94655092  0.78122781 11.62307343]
 [12.67236425  1.01543112  7.35544432  5.83939578  4.39760463 17.59002969
   4.86223981 16.33277462  4.15201307  3.05873476]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [23]:
x = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=x.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(x.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = x[z]
print(x)
print(R)

[[3 0 9 8 3 2 2 8 9 6]
 [5 6 1 6 5 4 0 4 8 8]
 [9 4 9 8 7 2 4 2 1 3]
 [1 1 4 1 1 1 3 0 4 1]
 [8 9 1 8 3 5 0 2 4 0]
 [3 6 4 9 2 3 1 7 2 0]
 [3 9 6 4 0 5 1 7 9 9]
 [2 3 6 0 7 8 4 4 6 4]
 [0 6 6 0 1 0 9 8 8 5]
 [9 9 2 6 8 2 0 6 2 8]]
[[0 0 0 0 0]
 [0 3 0 9 8]
 [0 5 6 1 6]
 [0 9 4 9 8]
 [0 1 1 4 1]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [24]:
x = np.arange(1,15,dtype=np.uint32)
y = stride_tricks.as_strided(Z,(11,4),(4,4))
print(y)

[[-9.58188978e-001 -1.19033065e-280 -9.11206018e-001  1.36055480e+088]
 [-1.19033065e-280 -9.11206018e-001  1.36055480e+088  4.35651379e-001]
 [-9.11206018e-001  1.36055480e+088  4.35651379e-001  5.80000442e-257]
 [ 1.36055480e+088  4.35651379e-001  5.80000442e-257 -1.67544251e-001]
 [ 4.35651379e-001  5.80000442e-257 -1.67544251e-001  3.49664115e-005]
 [ 5.80000442e-257 -1.67544251e-001  3.49664115e-005 -4.00580942e-001]
 [-1.67544251e-001  3.49664115e-005 -4.00580942e-001 -1.72450834e+199]
 [ 3.49664115e-005 -4.00580942e-001 -1.72450834e+199 -4.99578216e-001]
 [-4.00580942e-001 -1.72450834e+199 -4.99578216e-001  1.55822099e-092]
 [-1.72450834e+199 -4.99578216e-001  1.55822099e-092 -5.52812660e-001]
 [-4.99578216e-001  1.55822099e-092 -5.52812660e-001  2.38133805e+011]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [25]:
x = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(x) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [26]:
x = np.random.randint(0,10,50)
print(np.bincount(x).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [27]:
x = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (x.shape[0]-3)
j = 1 + (x.shape[1]-3)
C = stride_tricks.as_strided(x, shape=(i, j, n, n), strides=x.strides + x.strides)
print(C)

[[[[3 1 2]
   [2 2 4]
   [2 2 1]]

  [[1 2 3]
   [2 4 3]
   [2 1 0]]

  [[2 3 2]
   [4 3 0]
   [1 0 4]]

  [[3 2 3]
   [3 0 2]
   [0 4 0]]

  [[2 3 3]
   [0 2 1]
   [4 0 3]]

  [[3 3 2]
   [2 1 0]
   [0 3 4]]

  [[3 2 3]
   [1 0 2]
   [3 4 4]]

  [[2 3 1]
   [0 2 1]
   [4 4 4]]]


 [[[2 2 4]
   [2 2 1]
   [2 0 0]]

  [[2 4 3]
   [2 1 0]
   [0 0 0]]

  [[4 3 0]
   [1 0 4]
   [0 0 3]]

  [[3 0 2]
   [0 4 0]
   [0 3 0]]

  [[0 2 1]
   [4 0 3]
   [3 0 4]]

  [[2 1 0]
   [0 3 4]
   [0 4 1]]

  [[1 0 2]
   [3 4 4]
   [4 1 4]]

  [[0 2 1]
   [4 4 4]
   [1 4 0]]]


 [[[2 2 1]
   [2 0 0]
   [1 2 0]]

  [[2 1 0]
   [0 0 0]
   [2 0 3]]

  [[1 0 4]
   [0 0 3]
   [0 3 4]]

  [[0 4 0]
   [0 3 0]
   [3 4 0]]

  [[4 0 3]
   [3 0 4]
   [4 0 3]]

  [[0 3 4]
   [0 4 1]
   [0 3 1]]

  [[3 4 4]
   [4 1 4]
   [3 1 1]]

  [[4 4 4]
   [1 4 0]
   [1 1 3]]]


 [[[2 0 0]
   [1 2 0]
   [1 2 3]]

  [[0 0 0]
   [2 0 3]
   [2 3 3]]

  [[0 0 3]
   [0 3 4]
   [3 3 1]]

  [[0 3 0]
   [3 4 0]
   [3 1 1]]

  [[3 0 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [28]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  8  7 16 11]
 [ 8  3 10  8  7]
 [ 7 10  7 42  5]
 [16  8 42  9 13]
 [11  7  5 13  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [29]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [34]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

# alternative solution:
# Author: Sebastian Wallkötter (@FirefoxMetzger)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


AttributeError: ignored

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [35]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [36]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [37]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [38]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [39]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.69 s per loop
1 loop, best of 5: 173 ms per loop
10 loops, best of 5: 123 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [40]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [41]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 4 2]
 [1 3 4]
 [3 0 0]
 [1 2 3]
 [1 2 0]
 [4 3 0]
 [0 4 0]
 [0 2 1]
 [0 3 2]
 [0 2 0]]
[[4 4 2]
 [1 3 4]
 [3 0 0]
 [1 2 3]
 [1 2 0]
 [4 3 0]
 [0 4 0]
 [0 2 1]
 [0 3 2]
 [0 2 0]]
[[4 4 2]
 [1 3 4]
 [3 0 0]
 [1 2 3]
 [1 2 0]
 [4 3 0]
 [0 4 0]
 [0 2 1]
 [0 3 2]
 [0 2 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [43]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [44]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [45]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.06689193, 0.21835136, 0.15789918, 0.01130245, 0.06658101,
        0.1939582 , 0.18172644, 0.15071916, 0.00232645, 0.14048793],
       [0.1094579 , 0.35729694, 0.25837666, 0.01849464, 0.10894913,
        0.31738145, 0.29736613, 0.2466277 , 0.00380687, 0.22988593],
       [0.16188302, 0.52842518, 0.38212678, 0.0273527 , 0.16113058,
        0.46939206, 0.43979036, 0.36475063, 0.00563018, 0.33999035],
       [0.10742679, 0.35066694, 0.25358222, 0.01815146, 0.10692747,
        0.31149212, 0.29184821, 0.24205128, 0.00373623, 0.22562017],
       [0.02235673, 0.07297775, 0.05277332, 0.00377752, 0.02225281,
        0.06482503, 0.06073691, 0.0503736 , 0.00077755, 0.0469541 ],
       [0.11065738, 0.36121236, 0.26120806, 0.01869731, 0.11014304,
        0.32085946, 0.3006248 , 0.24933035, 0.00384859, 0.23240512],
       [0.10818434, 0.35313974, 0.25537041, 0.01827945, 0.10768149,
        0.31368867, 0.29390623, 0.24375815, 0.00376258, 0.22721117],
       [0.23594276, 0.77017402, 0.5569456

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [46]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [47]:
A = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
B = np.logical_and.reduce(np.mod(A, 1) == 0, axis=-1)
B &= (A.sum(axis=-1) == n)
print(A[B])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [49]:
A = np.random.randn(100) #1D array
N = 1000 # no. of bootstrap samples
B = np.random.randint(0, A.size, (N, A.size))
means = A[B].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.33801459 -0.0011284 ]
